-- ============================================================================
-- Migration: v1 → v2
-- ============================================================================
-- Änderungen:
--   1. Neue Tabellen: organization, department, join_department_rallye
--   2. Datenmigration: studiengang → department (mit neuer Organisation "DHBW Lörrach")
--   3. Datenmigration: tour_mode → organization.default_rallye_id
--   4. Spalten entfernen: rallye.studiengang, rallye.tour_mode
--   5. RLS-Policies für neue Tabellen
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. Neue Tabellen erstellen
-- ============================================================================

-- Tabelle: organization
CREATE TABLE IF NOT EXISTS "public"."organization" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" text NOT NULL,
    "default_rallye_id" bigint
);

ALTER TABLE "public"."organization" OWNER TO "postgres";

ALTER TABLE "public"."organization" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."organization_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."organization"
    ADD CONSTRAINT "organization_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."organization"
    ADD CONSTRAINT "organization_default_rallye_id_fkey" 
    FOREIGN KEY ("default_rallye_id") REFERENCES "public"."rallye"("id") ON DELETE SET NULL;


-- Tabelle: department
CREATE TABLE IF NOT EXISTS "public"."department" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" text NOT NULL,
    "organization_id" bigint NOT NULL
);

ALTER TABLE "public"."department" OWNER TO "postgres";

ALTER TABLE "public"."department" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."department_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."department"
    ADD CONSTRAINT "department_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."department"
    ADD CONSTRAINT "department_organization_id_fkey" 
    FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE CASCADE;


-- Tabelle: join_department_rallye
CREATE TABLE IF NOT EXISTS "public"."join_department_rallye" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "department_id" bigint NOT NULL,
    "rallye_id" bigint NOT NULL
);

ALTER TABLE "public"."join_department_rallye" OWNER TO "postgres";

ALTER TABLE "public"."join_department_rallye" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."join_department_rallye_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."join_department_rallye"
    ADD CONSTRAINT "join_department_rallye_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."join_department_rallye"
    ADD CONSTRAINT "join_department_rallye_department_id_fkey" 
    FOREIGN KEY ("department_id") REFERENCES "public"."department"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."join_department_rallye"
    ADD CONSTRAINT "join_department_rallye_rallye_id_fkey" 
    FOREIGN KEY ("rallye_id") REFERENCES "public"."rallye"("id") ON DELETE CASCADE;


-- ============================================================================
-- 2. Datenmigration: Organisation "DHBW Lörrach" erstellen
-- ============================================================================

-- Organisation erstellen (mit der ersten tour_mode=true Rallye als default)
INSERT INTO "public"."organization" ("name", "default_rallye_id")
SELECT 
    'DHBW Lörrach',
    (SELECT "id" FROM "public"."rallye" WHERE "tour_mode" = true ORDER BY "created_at" ASC LIMIT 1);


-- ============================================================================
-- 3. Datenmigration: Departments aus Studiengängen erstellen
-- ============================================================================

-- Einzigartige Studiengänge als Departments erstellen
INSERT INTO "public"."department" ("name", "organization_id")
SELECT DISTINCT 
    rallye."studiengang",
    (SELECT "id" FROM "public"."organization" WHERE "name" = 'DHBW Lörrach')
FROM "public"."rallye" AS rallye
WHERE rallye."studiengang" IS NOT NULL AND rallye."studiengang" != '';


-- ============================================================================
-- 4. Datenmigration: Rallyes mit Departments verknüpfen
-- ============================================================================

INSERT INTO "public"."join_department_rallye" ("department_id", "rallye_id")
SELECT 
    department."id",
    rallye."id"
FROM "public"."rallye" AS rallye
JOIN "public"."department" AS department ON department."name" = rallye."studiengang"
WHERE rallye."studiengang" IS NOT NULL AND rallye."studiengang" != '';


-- ============================================================================
-- 5. Spalten entfernen: studiengang und tour_mode
-- ============================================================================

ALTER TABLE "public"."rallye" DROP COLUMN IF EXISTS "studiengang";
ALTER TABLE "public"."rallye" DROP COLUMN IF EXISTS "tour_mode";


-- ============================================================================
-- 6. Row Level Security für neue Tabellen
-- ============================================================================

ALTER TABLE "public"."organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."department" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."join_department_rallye" ENABLE ROW LEVEL SECURITY;

-- Organization Policies
CREATE POLICY "Enable read access for all users" ON "public"."organization" 
    FOR SELECT USING (true);

CREATE POLICY "Enable write for authenticated users only" ON "public"."organization" 
    TO "authenticated" USING (true) WITH CHECK (true);

-- Department Policies
CREATE POLICY "Enable read access for all users" ON "public"."department" 
    FOR SELECT USING (true);

CREATE POLICY "Enable write for authenticated users only" ON "public"."department" 
    TO "authenticated" USING (true) WITH CHECK (true);

-- Join Department Rallye Policies
CREATE POLICY "Enable read access for all users" ON "public"."join_department_rallye" 
    FOR SELECT USING (true);

CREATE POLICY "Enable write for authenticated users only" ON "public"."join_department_rallye" 
    TO "authenticated" USING (true) WITH CHECK (true);


-- ============================================================================
-- 7. Grants für neue Tabellen
-- ============================================================================

GRANT ALL ON TABLE "public"."organization" TO "anon";
GRANT ALL ON TABLE "public"."organization" TO "authenticated";
GRANT ALL ON TABLE "public"."organization" TO "service_role";

GRANT ALL ON SEQUENCE "public"."organization_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."organization_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."organization_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."department" TO "anon";
GRANT ALL ON TABLE "public"."department" TO "authenticated";
GRANT ALL ON TABLE "public"."department" TO "service_role";

GRANT ALL ON SEQUENCE "public"."department_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."department_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."department_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."join_department_rallye" TO "anon";
GRANT ALL ON TABLE "public"."join_department_rallye" TO "authenticated";
GRANT ALL ON TABLE "public"."join_department_rallye" TO "service_role";

GRANT ALL ON SEQUENCE "public"."join_department_rallye_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."join_department_rallye_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."join_department_rallye_id_seq" TO "service_role";


COMMIT;

-- ============================================================================
-- Migration v1 → v2 abgeschlossen
-- ============================================================================
